version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/wanderlust
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 120
      runas: ubuntu
