version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm run installer
  build:
    commands:
      - echo "Building application..."
      - npm run build
      - echo "Build completed on `date`"
  post_build:
    commands:
      - echo "Creating deployment package..."
      - mkdir -p deployment
      # Copy backend
      - cp -r backend/dist deployment/backend
      - cp backend/package.json deployment/
      - cp backend/package-lock.json deployment/
      # Copy frontend
      - cp -r frontend/dist deployment/frontend
      - cp frontend/package.json deployment/frontend/
      # Copy scripts and configs
      - cp -r scripts deployment/
      - cp appspec.yml deployment/
      - echo "Creating deployment zip..."
      - cd deployment && zip -r ../wanderlust-deployment.zip .
artifacts:
  files:
    - wanderlust-deployment.zip
  discard-paths: yes
