version: 0.2

phases:
  install:
    commands:
      - echo "Debug started"
      - ls -la
      - ls -la scripts/
      - echo "Debug completed"

artifacts:
  files:
    - '**/*'
  base-directory: .
